# Generated by Django 6.0.4 on 2026-04-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('desc', models.TextField(blank=True, verbose_name='Описание товара')),
                ('price', models.PositiveIntegerField(help_text='Цена в копейках/центах', verbose_name='Цена (в минимальных единицах)')),
                ('currency', models.CharField(choices=[('usd', 'Доллар (США)'), ('eur', 'Евро'), ('rub', 'Российский рубль')], default='usd', max_length=3, verbose_name='Валюта')),
            ],
            options={
                'verbose_name': ('Товар',),
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
